### ISSUE TITLE
tcp连接的setkeepalive方法返回error

### ISSUE THREAD

**Issue by haifeng9414** [chronolaw/openresty_dev#1]
我直接使用仓库代码，运行`curl 127.1:81/cosocket -d "12|34|"`命令，得到的输出是：
```
12,
34,
failed to read data: closed
sock usedtimes = 0
receive from backend. len: 16 data: hellohellohello
```

usedtimes的值始终是0，`setkeepalive`方法执行失败，我把err打印出来，显示的是`invalid connection`，我在源码里看到这个错误信息的判断如下：
```
if (c->read->eof
        || c->read->error
        || c->read->timedout
        || c->write->error
        || c->write->timedout)
    {
        lua_pushnil(L);
        lua_pushliteral(L, "invalid connection");
        return 2;
    }
```

为了知道是哪个条件导致的失败，我这样修改源码：
```
if (c->read->eof)
    {
        lua_pushnil(L);
        lua_pushliteral(L, "read eof invalid connection");
        return 2;
    }

    if (c->read->error)
    {
        lua_pushnil(L);
        lua_pushliteral(L, "read error invalid connection");
        return 2;
    }

    if (c->read->timedout)
    {
        lua_pushnil(L);
        lua_pushliteral(L, "read timeout invalid connection");
        return 2;
    }

    if (c->write->error)
    {
        lua_pushnil(L);
        lua_pushliteral(L, "write error invalid connection");
        return 2;
    }

    if (c->write->timedout)
    {
        lua_pushnil(L);
        lua_pushliteral(L, "write timeout invalid connection");
        return 2;
    }
```

最后编译重现问题，日志显示错误信息为：`read eof invalid connection`。
请问这个问题如何避免，是缺少什么配置吗。

**Comment by chronolaw** [comment]
这段代码运行没有问题，提示信息“failed to read data”是读取完毕报出的，实际项目中可以不认为是错误。
read eof invalid connection很清楚地显示了原因。

sock usedtimes = 0也是正常的，因为它是新创建的cosocket，而不是从连接池里拿的，自然重用次数就是0了。

有不清楚的地方可以再问。

**Comment by haifeng9414** [comment]
> 这段代码运行没有问题，提示信息“failed to read data”是读取完毕报出的，实际项目中可以不认为是错误。
> read eof invalid connection很清楚地显示了原因。
> 
> sock usedtimes = 0也是正常的，因为它是新创建的cosocket，而不是从连接池里拿的，自然重用次数就是0了。
> 
> 有不清楚的地方可以再问。

感谢罗老师回复，你的书和极客时间上的课程我都买了，正在学习。
我明白`failed to read data: closed`这个信息可以忽略。

我直接用这个仓库的代码测试，没有做任何修改，想通过`setkeepalive`方法把`ngx.socket.tcp()`创建的cosocket保存到连接池中，但是由于`read eof invalid connection`这个错误导致保存失败，那应该如何避免这个问题呢，`service/backend/cosocket.lua`和`service/stream/cosocket.lua`文件里都是正常的tcp读写操作，《OpenResty完全开发指南》的8.3.5节说是可以复用连接的。

我的OpenResty版本是`openresty/1.15.8.2`

**Comment by chronolaw** [comment]
看明白了。

这是因为这个cosocket连接到了后端服务，代码在service/stream/cosocket.lua，这里的连接处理比较草率，没有keepalive，所以请求处理完之后就关闭了连接。

然后回到service/backend/cosocket.lua，因为连接被服务器关闭了，所以就不是有效的连接，那么也就无法keepalive了。

这个应该算是我写示例代码的一个失误吧，只是形式上正确，但写后端服务时给忘了处理。

**Comment by haifeng9414** [comment]
感谢回复:)

那后端服务应该如何处理才能支持长连接呢，我在`service/stream/cosocket.lua`里调用`sock:setkeepalive()`显示sock的setkeepalive属性是nil，不能被调用，我看官方文档说`ngx.req.socket()`返回的cosocket只有`receive`、`receiveuntil`和`send`这些方法。

我也试了修改listen的配置为`listen 900 so_keepalive=10s:10s:10`，但是感觉这个配置不是用来解决这个问题的，相反，既然存在`so_keepalive`这个配置，说明tcp服务器不会主动关闭连接，`read eof invalid connection`这个错看样子像是上游服务器主动关闭了连接，不明白为什么会这样，这两天刚开始学习OpenResty，问的比较低级，希望罗老师能指点一下。

**Comment by chronolaw** [comment]
http协议有长连接机制，但stream没有内置的长连接，就只能自己实现了，目前来看比较简单的做法就是一个连接过来后不关闭，用循环持续接收消息，这样就保持了与客户端的连接，再加上超时控制来关闭连接。

**Comment by haifeng9414** [comment]
明白了，感谢罗老师。
