### ISSUE TITLE
关于openresty的两个问题请教

### ISSUE THREAD

**Issue by lizhezyj** [chronolaw/openresty_dev#2]
老师您好：
      我看过您的完全开发指南后，有如下2个问题，需要请教
     (1)在LINUX平台上如何搭建eclipse的调试openresty的环境？
     我目前导入项目后可以调试NGINX的代码，但是如何调试LUA脚本代码？
      我在lua设置变量的C模块代码ngx_stream_lua_add_variable函数中增加断点，为什么DEBUG方式启动openresty之后无法进入断点？
     (2)我想通过lua脚本中设置变量后，在nginx代码中给此变量赋值，然后在您例子中的conf文件中获取此变量，这样是否可行？
lua_add_variable $new_var;

server {
    listen 785;
    preread_by_lua_block {
    		ngx.log(ngx.ERR, "lua start preread 785")
        assert(not ngx.var.new_var)
--        ngx.var.new_var = 'hello111'
         ngx.say(ngx.var.new_var)
         	ngx.log(ngx.ERR, "lua end preread 785")
    }
     proxy_connect_timeout 10s;
     proxy_timeout 30s;
     proxy_pass NAME2; 
}          
是否可以在NGINX中的STREAM代码中设置new_var变量，然后在这个LUA中打印出来？

**Comment by chronolaw** [comment]
目前暂时没有lua代码的调试办法，只能打日志。可以调试C代码，eclipse没用过。
ngx_stream_lua_add_variable函数需要写指令才能触发吧。
这个需要看add_variable和preread这两个指令执行的先后顺序，必须在前面的阶段设置，后面才能看到值，最好是做实验实际验证。

有这样的钻研精神就很好，得出结果在这里也给大家都分享一下。

**Comment by lizhezyj** [comment]
调试的问题，解决了，主要是需要把断点放到bulid目录中的代码中就可以了，我原来是放到bundle中了，使用eclipse+cdt可以调试

**Comment by lizhezyj** [comment]
在stream的session中如何获取ngx_conf_t句柄，

**Comment by lizhezyj** [comment]
老师，在框架中使用代码修改变量内容的方法，我调研测试了，如下：
首先在CONF文件中的stream中增加便令new_var
upstream NAME2 {
         hash $remote_addr consistent;
         server 172.16.100.66:1024 max_fails=3 fail_timeout=30s;
}

# nc 127.1 785
lua_add_variable $new_var;

server {
    listen 785 ssl;
    ssl_certificate      /usr/local/openresty-1.13.6.2/nginx/cert/server.crt;
    ssl_certificate_key  /usr/local/openresty-1.13.6.2/nginx/cert/server.key;
    
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m; 
    ssl_session_tickets  off;
    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;
    preread_by_lua_block {
    		ngx.log(ngx.ERR, "lua start preread 785")
         	ngx.log(ngx.ERR, "lua end preread 785")
               ngx.log(ngx.ERR, ngx.var.new_var)
    }
     proxy_connect_timeout 10s;
     proxy_timeout 30s;
     proxy_pass NAME2; 
          
#     error_log    logs/streamlog.log    error;         
}

在ngx_stream_lua_preread_handler函数中增加
//////////男生 lizhezyj
        ngx_str_t varname=ngx_string("new_var");
        ngx_str_t *val;
        u_char *lowcase;
        ngx_uint_t	key;
        ngx_stream_variable_t *v;
        ngx_stream_variable_value_t *vv;
        u_char * sessionid;
        /* get variable */
		lowcase = ngx_pcalloc(s->connection->pool, varname.len + 1);
		if (lowcase != NULL) {

			key = ngx_hash_strlow(lowcase, varname.data, varname.len);
			lowcase[varname.len] = 0;

			v = ngx_hash_find(&cmcf->variables_hash, key, lowcase, varname.len);
			if (v) {
				//if (!(v->flags & NGX_STREAM_VAR_CHANGEABLE)) {
					//vv=&s->variables[v->index];
					s->variables[v->index].data = ngx_palloc(s->connection->pool, 129);
					if (s->variables[v->index].data != NULL) {
						u_char *p;
						p=ngx_copy(s->variables[v->index].data,"1111111111",10);
						s->variables[v->index].len=10;
						s->variables[v->index].valid=1;
						s->variables[v->index].not_found = 0;
						s->variables[v->index].no_cacheable = 0;

					}
				//}				

			}

		}
		///////////
使用自己开发的SSL客户端连接openresty，产生的日志如下
2020/11/05 10:24:01 [error] 7290#0: *1 stream [lua] preread_by_lua(basic.conf:29):9: 1111111111 while prereading client data, client: 172.16.100.66, server: 0.0.0.0:785

证明了我的解决方法可行
